### PR TITLE
Blockgen refactor; Added upload to S3; Make generation concurrent.

### PR DESCRIPTION
**Pull request by bwplotka**
Signed-off-by: Bartek Plotka <bwplotka@gmail.com>

Example usage:

```
go run cmd/thanosbench blockgen --workers=100 --output.objstore.config-file=<s3-aws-bucket.yaml> --output.dir=./genblocks --config="
rangeBasedBlocks:
- blocks: [ 2h ]
  startTime: 2019-10-16T00:00:00
  series:
  - labels:
      __name__: container_memory_usage_bytes
      job: kubelet
      namespace: default
      pod: yolo-554c585fc6-2p7gg
      node: minikube
    targets: 10000
    # Val generation options:
    type: GAUGE
    scrapeInterval: 15s
    changeInterval: 1h
    jitter: 30000000
    max: 200000000
    min: 10000000
  externalLabels:
    replica: 1
    cluster: bartek_laptop
    source: blockgen
"
```

It takes:
*  `~5s` for 8h 10k series
* `~14s` for 24h 10k series
*  `~1m` for 48h 10k series (freezes all ;p)
* `~15s` for 2h 100k series.

Sizes are super small. This is because: 
* chunks are perfectly full and aligned
* while there are k cardinality, there are not many unique labels.

BTW, when I accidentally set chunk size to 1, we got 20x size (: 

I think that's good enough for now. Definitely triggers memory issues on store/querier..

### CODE REVIEW

**Comment by bwplotka** [comment]
It explodes with memory, some profiling is needed, but it's good enough.

Good enough to kill  with query request.

**Comment by ppanyukov** [comment]
This is quite a big PR....

My general sentiment: 

- Are we not overcomplicating things?
- Are we not adding things that we don't need?
- The dumber the code the better? At least for my level of brain power :)


A couple of examples:

- S3 sync. Does it really need to be part of "blockgen" command? Use blockgen to create blocks on disk. Use whatever other tools to sync to wherever you want.

- Execution in parallel. Is this really required? If so, maybe make it external to `pkg/blockgen/Generator`?

- YAML config. Isn't it better to have flat YAML config and Go type for it in `cmd/blockgen.go` and then translate to whatever pkg-specific configs as required? See next comment.

- Reuse and embedding of types in YAML config types. Reuse is good but right now it's a quite a long chain to navigate. By the time I get to the leaf I already forgotten why I'm there. Flat config might work better if it's in `cmd`? Example:

```
// Current config type, quite long chain of clicks to
// understand what exactly this config is.
type GeneratorConfig struct {
	RangeBasedBlocks []RangesBasedConfig `yaml:"rangeBasedBlocks"`
	Blocks           []BlockConfig       `yaml:"blocks"`
}
```

```
type FlatConfig struct {
	EmbeddedType struct {
		SomeValue string `yaml:"some-value"`
	} `yaml:"stuff"`

	ArrayOfEmbeddedThings []struct {
		AnotherVal string `yaml:"another-val"`
	} `yaml:"array"`
}
```

- Do we really need `type SeriesSet interface`?  Also the new value generators, why do they need to care about time, e.g. `ScrapeInterval` etc?


- Nit: magic `int64`s everywhere! E.g. `func rangeForTimestamp(t int64, width int64) (maxt int64)`. Isn't it better to use `time.Time` and `time.Duration`? I appreciate that TSDB uses `int64` for perf reasons but we certainly don't need this? 

- Nit: docs.

**Comment by bwplotka** [comment]
> This is quite a big PR....

Yup sorry for that.

> S3 sync. Does it really need to be part of "blockgen" command? Use blockgen to create blocks on disk. Use whatever other tools to sync to wherever you want.

I did it intentionally to save local disk space. It might be not needed indeed. Happy to separate in this PR. Maybe even use thanos.Shipper for it?

> Execution in parallel. Is this really required? If so, maybe make it external to pkg/blockgen/Generator?

I would vote for having this in our package as it enormously makes things faster. You can do it sequentially with worker=1 if you want.

> YAML config. Isn't it better to have flat YAML config and Go type for it in cmd/blockgen.go and then translate to whatever pkg-specific configs as required? See next comment.
> Reuse and embedding of types in YAML config types. Reuse is good but right now it's a quite a long chain to navigate. By the time I get to the leaf I already forgotten why I'm there. Flat config might work better if it's in cmd? Example:

I see this idea for embedded string, but not entirely sure if it is possible. This is because it conflicts with the flexibility of options. I think we should ask ourselves a question - are we aiming for ease of use or flexibility? e.g We might just give tool that takes [a, b] time ranges and maybe type of generator with params. This is great but normal use case is to have many blocks that are aligned in a certain way, so technically just passing 1h, 2h, 8h 8h 8h is nicer, but it blocks advanced options allowed by just `generate one block`. So the current config allows both. Maybe it should be different CLIs  subcommands for that? 

> Do we really need type SeriesSet interface? 

Yes, if we want some kind of "steaming" for the generation of series.

Also the new value generators, why do they need to care about time, e.g. ScrapeInterval 

* So random one does not, but generators that tries to mimic gauge or counter.. they kind of need this. It also fits into `Appender` interface, so why not? I don't see why it adds complexity. Timestamp needs to be defined and if not in generator it would be needed to be maintained somewhere else. 

> Nit: magic int64s everywhere! E.g. func rangeForTimestamp(t int64, width int64) (maxt int64). Isn't it better to use time.Time and time.Duration? I appreciate that TSDB uses int64 for perf reasons but we certainly don't need this?

I think it's also the fact we use TSDB functions/code so we have to, right?

> Nit: docs.

Yes! Will do in next PR.

**Comment by bwplotka** [comment]
Thanks! 

> I was thinking more in terms of: why not have these just produce values in a sequence. Why do they even care about time and scrape interval etc? Wouldn't it much easier to not care about it on this level and have every counter implementation think about this and instead add timestamps at a level where these sequences get consumed?

 I think timestamps makes sense as it fits into SerieSet again. And I responded below why I think this makes sense.

> Well yes but wouldn't it be nice to minimise these? And maybe just convert to TSDB-specific ints right at the point of direct interaction with TSDB? There are probably not that many points like this but I may be wrong.

Consistency is a key as well: It just easier if we use `int64` everywhere.

> Is channel not sufficient for example? Or we try to avoid channels? What about just having this for interface func Next() (labels.Labels, float64[]) or similar. Just thinking aloud here.

Same as above. This will work, but it's not consistent with TSDB. Anything we do will be approx hard to understand by new comer. At least we have one less thing to learn though as Series Set is already everywhere in Thanos and TSDB. So consistency argument wins to me (: 

OK, what's I am going to fix in this PR:
* Move sync to separate command
* Remove configs completely - do common profiles instead as you did in initially - I think that makes more sense! :+1: It is just easier for us to tell what's "natural". Still, you can configure your own blocks if needed. Let's aim for simplistic usage!

**Comment by ppanyukov** [comment]
> OK, what's I am going to fix in this PR:

yep, agreed :)

**Comment by bwplotka** [comment]
Merging on green as agreed offline with @ppanyukov

**Pull request merged**
